# Generated by Django 3.0.6 on 2020-06-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('lat', models.FloatField(default=0.0)),
                ('longit', models.FloatField(default=0.0)),
                ('primary_poc', models.CharField(default='', max_length=30)),
                ('sales_rep_id', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('standard_qty', models.IntegerField(blank=True, null=True)),
                ('gloss_qty', models.IntegerField(blank=True, null=True)),
                ('poster_qty', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('standard_amt_usd', models.FloatField(blank=True, null=True)),
                ('gloss_amt_usd', models.FloatField(blank=True, null=True)),
                ('poster_amt_usd', models.FloatField(blank=True, null=True)),
                ('total_amt_usd', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReps',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('regio_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_reps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='table_ins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'table_ins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'web_events',
                'managed': False,
            },
        ),
    ]
